/**
 * Registry reporter — produces toolcalls.yaml.
 *
 * Generates YAML documenting all tool calls with side effects,
 * grouped by severity: NO CHECKS → PARTIAL CHECKS → CONFIRMED.
 *
 * Mirrors `reporter/registry.py` from the Python version.
 */

import type { ScanResult, Tool } from "../models.js";

// ---------------------------------------------------------------------------
// Effect-type priority groups for NO CHECKS ordering
// ---------------------------------------------------------------------------

const EFFECT_PRIORITY: [number, Set<string>][] = [
  [0, new Set(["payment", "database_delete", "dynamic_code", "file_delete"])],
  [1, new Set(["llm_call", "agent_invocation"])],
  [2, new Set(["database_write", "http_write", "destructive"])],
  [3, new Set(["email", "messaging", "publish"])],
];

function effectPriority(tool: Tool): number {
  const categories = new Set(tool.sideEffects.map(se => se.category));
  for (const [priority, group] of EFFECT_PRIORITY) {
    for (const cat of categories) {
      if (group.has(cat)) return priority;
    }
  }
  return 4;
}

// ---------------------------------------------------------------------------
// YAML helpers (no external dependency beyond the `yaml` package)
// ---------------------------------------------------------------------------

function yamlEscape(s: string): string {
  if (!s) return '""';
  const needsQuote = /[:#{}[\],&*?|\-<>=!%@`"'\n/]/.test(s) ||
    s.startsWith(" ") || s.endsWith(" ");
  if (needsQuote) {
    const escaped = s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    return `"${escaped}"`;
  }
  return s;
}

function renderToolEntry(tool: Tool, includeConfirmed = false): string {
  const lines: string[] = [];
  lines.push(`  - function: ${tool.function}`);
  lines.push(`    file: ${tool.file}`);
  lines.push(`    line: ${tool.line}`);

  // actions
  if (tool.sideEffects.length > 0) {
    lines.push("    actions:");
    for (const se of tool.sideEffects) {
      lines.push(`      - ${yamlEscape(se.code)}`);
    }
  } else {
    lines.push("    actions: []");
  }

  // checks
  if (tool.guards.length > 0) {
    lines.push("    checks:");
    for (const g of tool.guards) {
      lines.push(`      - type: ${g.type}`);
      lines.push(`        code: ${yamlEscape(g.code)}`);
    }
  } else {
    lines.push("    checks: []");
  }

  // missing
  if (tool.missingHints.length > 0) {
    lines.push("    missing:");
    for (const hint of tool.missingHints) {
      lines.push(`      - ${yamlEscape(hint)}`);
    }
  } else {
    lines.push("    missing: []");
  }

  // confirmed
  if (includeConfirmed && tool.confirmed) {
    lines.push(`    confirmed: ${yamlEscape(tool.confirmed)}`);
  }

  // owasp
  if (tool.owaspAgentic.length > 0) {
    lines.push(`    owasp: [${tool.owaspAgentic.join(", ")}]`);
  } else {
    lines.push("    owasp: []");
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate the canonical toolcalls.yaml content.
 * Output conforms to spec_version 1.0.
 *
 * Key invariants:
 * - Tools grouped: NO CHECKS → PARTIAL CHECKS → CONFIRMED
 * - Within NO CHECKS, ordered by severity priority then function name
 * - actions[] strings do NOT include line numbers (diff-stable)
 * - 2-space indent, snake_case field names
 */
export function generateToolcallsYaml(result: ScanResult): string {
  const lines: string[] = [];

  // Header comment
  lines.push("# toolcalls.yaml");
  lines.push("# What your agent can do to the real world — and what checks exist.");
  lines.push("# Generated by diplomat-agent-ts · https://diplomat.run");
  lines.push("#");
  lines.push("# Commit this file. Review changes in PRs.");
  lines.push("# In source code:");
  lines.push("#   Fix          → add validation, the next scan picks it up");
  lines.push("#   Acknowledge  → add  # checked:ok  to confirm you've reviewed it");
  lines.push("#   Protected elsewhere → add  # checked:ok — protected by [middleware/gateway/etc]");
  lines.push("#   CI enforcement → --fail-on-unchecked blocks PRs with new unreviewed tool calls");
  lines.push("");

  // Metadata (snake_case keys)
  lines.push(`generated: "${result.generated}"`);
  lines.push(`version: "${result.version}"`);
  lines.push(`spec_version: "${result.specVersion}"`);
  lines.push(`path: "${result.path}"`);
  lines.push(`language: ${result.language}`);
  lines.push("");

  // Summary
  lines.push("summary:");
  lines.push(`  total: ${result.summary.total}`);
  lines.push(`  no_checks: ${result.summary.noChecks}`);
  lines.push(`  partial_checks: ${result.summary.partialChecks}`);
  lines.push(`  confirmed: ${result.summary.confirmed}`);
  lines.push("");

  // Classify tools
  const noChecks: Tool[] = [];
  const partialChecks: Tool[] = [];
  const confirmed: Tool[] = [];

  for (const tool of result.tools) {
    if (tool.status === "confirmed") {
      confirmed.push(tool);
    } else if (tool.status === "no_checks") {
      noChecks.push(tool);
    } else {
      partialChecks.push(tool);
    }
  }

  lines.push("tool_calls:");

  // Section 1: NO CHECKS — grouped by effect priority
  if (noChecks.length > 0) {
    // Group by effect priority
    const groups = new Map<number, Tool[]>();
    for (const tool of noChecks) {
      const p = effectPriority(tool);
      if (!groups.has(p)) groups.set(p, []);
      groups.get(p)!.push(tool);
    }

    for (const priority of [...groups.keys()].sort()) {
      const toolsInGroup = groups.get(priority)!;
      // Build group label from categories present in this priority group
      const allCats = new Set<string>();
      for (const tool of toolsInGroup) {
        for (const se of tool.sideEffects) {
          const [, groupCats] = EFFECT_PRIORITY[priority] ?? [priority, new Set()];
          if (groupCats.has(se.category)) allCats.add(se.category);
        }
      }
      const label = [...allCats].sort().join(" / ") || "other";
      lines.push("");
      lines.push(`  # ⚠ NO CHECKS — ${label}`);
      for (const tool of [...toolsInGroup].sort((a, b) => a.function.localeCompare(b.function))) {
        lines.push(renderToolEntry(tool));
        lines.push("");
      }
    }
  }

  // Section 2: PARTIAL CHECKS
  if (partialChecks.length > 0) {
    lines.push("");
    lines.push("  # ~ PARTIAL CHECKS");
    for (const tool of [...partialChecks].sort((a, b) => a.function.localeCompare(b.function))) {
      lines.push(renderToolEntry(tool));
      lines.push("");
    }
  }

  // Section 3: CONFIRMED
  if (confirmed.length > 0) {
    lines.push("");
    lines.push("  # ✓ CONFIRMED");
    for (const tool of [...confirmed].sort((a, b) => a.function.localeCompare(b.function))) {
      lines.push(renderToolEntry(tool, true));
      lines.push("");
    }
  }

  return lines.join("\n") + "\n";
}
